### ISSUE TITLE
Feature request: pre-commit hook to run automatically before each commit

### ISSUE THREAD

**Issue by danhje** [jllorencetti/pytest-deadfixtures#37]
What the title says :)

**Comment by AIGeneratedUsername** [comment]
@danhje Did you try:

```yaml
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "pytest-deadfixtures",  # TODO: Double-check that plugin name is correct
          ]

```
